### ISSUE TITLE
How to sort Dynamic Uitableview cell.

### ISSUE THREAD

**Issue by onetwoth** [bsorrentino/BSCButtonBar#1]
How to sort Dynamic UITableView cell?

**Comment by bsorrentino** [comment]
Hi 

Do you mean: How to sort data within table?

If Yes , it is enough that you perform ordering upon datasource and call 

``` ObjectiveC
[self.tableView reloadData];
```

If No ... could you explain little bit better which is your need ?

**Comment by onetwoth** [comment]
My UITableViewCell Contain Files Date, Files Type,File Size, File Name.
So, I want to sort tableViewCell as per Files Date, as per Files Type, as per File Size & File Name.

Any Help would be apraciated.

**Comment by bsorrentino** [comment]
Assuming that you have an NSArray of FileData as UITable's dataSource, you could use, on ButtonBar selection, the following code 

``` ObjectiveC

NSArray *arrayToSort = [[NSMutableArray alloc] initWithArray:self.dataSource copyItems:NO]; 

self.dataSource = [arrayToSort sortedArrayUsingComparator:^NSComparisonResult(id a, id b) {
    NSDate *first = [(FileData*)a size];
    NSDate *second = [(FileData*)b size];
    return first -second;
}];

[self.tableView reloadData]
```

**Comment by onetwoth** [comment]
I have  FilesCreatedTime, FilesName, FilesSize, FilesExtensionType this 4 NSMutableArray.
so, I want to sort By Name, sort By Size, sort By Extension Type, sort By created Time in ascending order as per demand.

**Comment by bsorrentino** [comment]
### 1st Solution (preferred)

I suggest you to join all the arrays in one, that will contain an Object (e.g. FileData) with all the desired attributes

Once done it, you could use the solution above

### 2nd Solution

Create a readonly property named _dataSource_ that will return the right array depending upon a sort filter

``` Objective-C
// definition
@property (nonatomic,weak,readonly) NSArray *dataSource;
@property () NSInteger sortFilter;

// Implementation

(-) NSArray * dataSource 
{
    switch( sortFilter ) {
    case  SIZE:
      return self.arrayOfTimes;
      break;
    case  NAME:
      return self.arrayOfNames;
      break;
 .....
    }
}
```
